# Generated by Django 6.1.1 on 2026-09-25 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("LANGCHAIN", "LangChain"),
                            ("CREWAI", "CrewAI"),
                            ("AUTOGEN", "AutoGen"),
                            ("LYZR", "Lyzr Core"),
                            ("CUSTOM", "Custom Python/FastAPI"),
                        ],
                        default="LYZR",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building UI/Agent"),
                            ("READY", "Ready"),
                            ("DEPLOYED", "Deployed"),
                            ("FAILED", "Deployment Failed"),
                        ],
                        default="BUILDING",
                        max_length=20,
                    ),
                ),
                ("github_repo_url", models.URLField(blank=True, null=True)),
                ("live_deployment_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("AGENT", "Architect Assistant"),
                            ("SYSTEM", "System Log"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("code_snippet", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="workspace.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=255)),
                ("goal", models.TextField()),
                ("tools", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="workspace.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("NON_TECH", "Business Executive / Non-Technical"),
                            ("DEV", "Developer / Technical"),
                        ],
                        default="NON_TECH",
                        max_length=20,
                    ),
                ),
                (
                    "github_access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
